# fly.toml app configuration file generated for busybee on 2025-12-10T13:21:41+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'busybee'
primary_region = 'ams'

[build]
  dockerfile = '../../apps/busybee-fe/Dockerfile'

  [build.args]
    NG_APP_API_URL = '${NG_APP_API_URL}'
    NG_APP_FIREBASE_API_KEY = '${NG_APP_FIREBASE_API_KEY}'
    NG_APP_FIREBASE_APP_ID = '${NG_APP_FIREBASE_APP_ID}'
    NG_APP_FIREBASE_AUTH_DOMAIN = '${NG_APP_FIREBASE_AUTH_DOMAIN}'
    NG_APP_FIREBASE_MEASUREMENT_ID = '${NG_APP_FIREBASE_MEASUREMENT_ID}'
    NG_APP_FIREBASE_MESSAGING_SENDER_ID = '${NG_APP_FIREBASE_MESSAGING_SENDER_ID}'
    NG_APP_FIREBASE_PROJECT_ID = '${NG_APP_FIREBASE_PROJECT_ID}'
    NG_APP_FIREBASE_STORAGE_BUCKET = '${NG_APP_FIREBASE_STORAGE_BUCKET}'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
