name: Deploy Frontend to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'apps/busybee-fe/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy frontend to Fly.io
        run: flyctl deploy --config apps/busybee-fe/fly.toml -a busybee
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
